### ISSUE TITLE
Fix Google Oauth client

### ISSUE THREAD

**Issue by ThisIsNoZaku** [Neone-character-creator/neone-character-creator-core#4]
When testing logging in, Google reported "deleted_client"

**Comment by ThisIsNoZaku** [comment]
Updated the client id, now after logging in
```
Method [public void io.github.thisisnozaku.charactercreator.controllers.SecurityController.googleLogin(com.google.api.services.plus.model.Person,javax.servlet.http.HttpSession) throws java.io.IOException]
Resolved arguments: 
[0] [type=org.springframework.validation.support.BindingAwareModelMap] [value={}]
[1] [type=org.apache.catalina.session.StandardSessionFacade] [value=org.apache.catalina.session.StandardSessionFacade@3e018f39]
] with root cause

java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
```

**Comment by ThisIsNoZaku** [comment]
No default constructor for entity:  : io.github.thisisnozaku.charactercreator.authentication.User; nested exception is org.hibernate.InstantiationException: No default constructor for entity:  : io.github.thisisnozaku.charactercreator.authentication.User
